In [3]:
import torch
import numpy as np

t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)

In [4]:
print(ft.shape)


torch.Size([2, 2, 3])


In [9]:
print(ft.view([-1, 2])) # ft라는 텐서를 (?, 3)의 크기로 변경
print(ft.view([-1, 2]).shape)
print(ft.shape)

tensor([[ 0.,  1.],
        [ 2.,  3.],
        [ 4.,  5.],
        [ 6.,  7.],
        [ 8.,  9.],
        [10., 11.]])
torch.Size([6, 2])
torch.Size([2, 2, 3])


In [19]:
lt = torch.Tensor([1, 2, 3, 4])
print(lt.dtype)# 기본으로 torch.float32로 선언됨
lt=lt.to(device='cuda', dtype=torch.float64) # GPU 연산을 위해 타입 변경
print(lt.dtype)# torch.float64로 선언됨 cuda.torch.float64가 아니네? 시밤?

torch.float32
torch.float64


In [38]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])
c=torch.cat([x, y], dim=0)      #torch.Size([4, 2]) 
print(c.shape,'\n\n',c,'\n\n')
d=torch.stack([x, y], dim=0)    #torch.Size([2, 2, 2]) 한번 감싸고(unsqueeze) 그리고 합침.(내부 연산이 있음)
print(d.shape,'\n\n',d)

torch.Size([4, 2]) 

 tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]]) 


torch.Size([2, 2, 2]) 

 tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])
